### ISSUE TITLE
Question about backward order

### ISSUE THREAD

**Issue by yihua7** [r4dl/StopThePop-Rasterization#3]
Hi,
Great job! I am confused with the code here: https://github.com/r4dl/StopThePop-Rasterization/blob/d8cad09919ff49b11be3d693d1e71fa792f559bb/cuda_rasterizer/backward.cu#L510. The paper says the backward order is the same as the forward, however, the code here still follows the inverse order as in original implementation.

**Comment by r4dl** [comment]
Hi,
this is the original 3DGS implementation, not ours - check out our implementation here:

https://github.com/r4dl/StopThePop-Rasterization/blob/d8cad09919ff49b11be3d693d1e71fa792f559bb/cuda_rasterizer/stopthepop/hierarchical_render.cuh#L1039

Best,
Lukas

**Comment by yihua7** [comment]
Thanks a lot! :)
